### PR TITLE
Loosen black and django requirements

### PR DESCRIPTION
**Pull request by powellc**
A small PR to loosen the requirements on black and django so that I can use this library with poetry, which does stricter requirements matching that some other python tools.  No problem if this doesn't work for you, but I'm using this happily in my project using my fork.

### CODE REVIEW

**Comment by powellc** [comment]
Thanks so much for the quick merge @larsvonschaff 💛

**Comment by larsvonschaff** [comment]
Thanks for the PR @powellc !

**Comment by powellc** [comment]
Not sure what the process is, but any chance you can push 1.0.9 up to PyPI? No rush, though ... I unblocked myself for now using a git link in requirements.

**Comment by larsvonschaff** [comment]
Done. If you have any other blockers you can either open another PR or drop me an email at larsvonschaff@gmail.com. I will try to be as helpful as possible.

**Comment by powellc** [comment]
You are a prince among men/women/people! Thank you 🙇🏽

**Pull request merged**
